# Generated by Django 4.1.3 on 2022-12-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('uploads', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'ProfessionalAccomplishments',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('uploads', models.ImageField(upload_to='images/awards')),
            ],
            options={
                'db_table': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
                ('uploads', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'DLC',
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=4000)),
                ('workField', models.CharField(blank=True, max_length=4000)),
                ('careersum', models.CharField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='VCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'VCS',
            },
        ),
    ]
