# Generated by Django 4.1.3 on 2022-12-04 03:11

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
